const SUPABASE_URL = 'https://afrtllehytzyeyurlfvr.supabase.co';
const SUPABASE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFmcnRsbGVoeXR6eWV5dXJsZnZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODM1MzY5OTgsImV4cCI6MjA5OTExMjk5OH0.rgmIHH5G9RFQgnRV6RIxmC1aVZpBxc8ehBzrEYAygis';

window.supabaseClient = supabase.createClient(SUPABASE_URL, SUPABASE_KEY);
